// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.7.0_@types+node@18.17.12_eslint@8.48.0_rollup@3.28.1_typescript@4.9.5/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.7.0_@types+node@18.17.12_eslint@8.48.0_rollup@3.28.1_typescript@4.9.5/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.7.0_@types+node@18.17.12_eslint@8.48.0_rollup@3.28.1_typescript@4.9.5/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.7.0_@types+node@18.17.12_eslint@8.48.0_rollup@3.28.1_typescript@4.9.5/node_modules/nuxt/dist/app/plugins/router").default> &
  InjectionType<typeof import("../../../src/runtime/plugin").default> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@3.7.0_@types+node@18.17.12_eslint@8.48.0_rollup@3.28.1_typescript@4.9.5/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../plugins/openFetch").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
