// Generated by nuxt-open-fetch
import type { OpenFetchOptions } from '/Users/tarasbatenkov/Projects/nuxt-open-fetch/src/module'
import type { OpenFetchClient, UseOpenFetchClient, UseLazyOpenFetchClient } from '/Users/tarasbatenkov/Projects/nuxt-open-fetch/src/clients'

import type { paths as PetsPaths } from '#build/types/nuxt-open-fetch/pets'

export type OpenFetchClientName = 'pets'

declare module '#app' {
  interface NuxtApp {
    $openFetch: Record<OpenFetchClientName, OpenFetchOptions>
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $openFetch: Record<OpenFetchClientName, OpenFetchOptions>
  }
}

export declare const $petsFetch: OpenFetchClient<PetsPaths>
export declare const usePetsFetch: UseOpenFetchClient<PetsPaths>
export declare const useLazyPetsFetch: UseLazyOpenFetchClient<PetsPaths>

export {}
